
  create table "public"."product_details" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "product_id" uuid not null,
    "language" character varying not null,
    "source_url" text not null,
    "description" text not null,
    "features" json not null,
    "safety_sheet_url" text not null
      );


alter table "public"."product_details" enable row level security;

alter table "public"."products" drop column "deprecated_stock";

alter table "public"."products" drop column "name";

alter table "public"."products" drop column "specs";

alter table "public"."products" add column "code" text;

alter table "public"."products" alter column "id" set default gen_random_uuid();

alter table "public"."products" alter column "image_url" set not null;

alter table "public"."products" alter column "is_active" drop default;

alter table "public"."products" alter column "price" set default NULL::numeric;

CREATE UNIQUE INDEX product_details_pkey ON public.product_details USING btree (id);

alter table "public"."product_details" add constraint "product_details_pkey" PRIMARY KEY using index "product_details_pkey";

alter table "public"."product_details" add constraint "product_details_product_id_fkey1" FOREIGN KEY (product_id) REFERENCES public.products(id) not valid;

alter table "public"."product_details" validate constraint "product_details_product_id_fkey1";

grant delete on table "public"."product_details" to "anon";

grant insert on table "public"."product_details" to "anon";

grant references on table "public"."product_details" to "anon";

grant select on table "public"."product_details" to "anon";

grant trigger on table "public"."product_details" to "anon";

grant truncate on table "public"."product_details" to "anon";

grant update on table "public"."product_details" to "anon";

grant delete on table "public"."product_details" to "authenticated";

grant insert on table "public"."product_details" to "authenticated";

grant references on table "public"."product_details" to "authenticated";

grant select on table "public"."product_details" to "authenticated";

grant trigger on table "public"."product_details" to "authenticated";

grant truncate on table "public"."product_details" to "authenticated";

grant update on table "public"."product_details" to "authenticated";

grant delete on table "public"."product_details" to "service_role";

grant insert on table "public"."product_details" to "service_role";

grant references on table "public"."product_details" to "service_role";

grant select on table "public"."product_details" to "service_role";

grant trigger on table "public"."product_details" to "service_role";

grant truncate on table "public"."product_details" to "service_role";

grant update on table "public"."product_details" to "service_role";


